export const FETCH_LOCATION = 'FETCH_LOCATION'
export const FETCH_LOADING = 'FETCH_LOADING'
export const DELETE_LOCATION = 'DELETE_LOCATION'
export const ADD_LOCATION = 'ADD_LOCATION'
export const UPDATE_LOCATION = 'UPDATE_LOCATION'
export const SORT_LOCATION_BY_NAME = 'SORT_LOCATION_BY_NAME'
export const SORT_LOCATION_BY_DATE_CREATED = 'SORT_LOCATION_BY_DATE_CREATED'
export const FETCH_SPECIFIC_LOCATION = "FETCH_SPECIFIC_LOCATION";

//COMMENT TYPES
export const COMMENT_LOADING = 'COMMENT_LOADING'
export const ADD_COMMENT = 'ADD_COMMENT'
export const GET_COMMENT = 'GET_COMMENT'
export const UPDATE_COMMENT = 'UPDATE_COMMENT'
export const DELETE_COMMENT = 'DELETE_COMMENT'
export const FETCH_SPECIFIC_COMMENT = 'FETCH_SPECIFIC_COMMENT'
export const GET_COMMENT_AUTHOR = 'GET_COMMENT_AUTHOR'

//AUTH TYPES
export const REGISTER_USER = 'REGISTER_USER'
export const REGISTER_USER_FAIL = 'REGISTER_USER_FAIL'
export const LOGIN_USER = 'LOGIN_USER'
export const LOGIN_USER_FAIL = 'LOGIN_USER_FAIL'
export const USER_LOADED = 'USER_LOADED'
export const USER_LOADED_FAIL = 'USER_LOADED_FAIL'

//ERROR TYPES
export const LOCATION_ERROR = 'LOCATION_ERROR'